### PR TITLE
refactored project and deleted redundant code

### PR DESCRIPTION
**Pull request by Teqwon-Norman**
Just refactored the entire project everything runs smoothly

### CODE REVIEW

**Review by Teqwon-Norman — COMMENTED** [review]
Great work with calculator.cpp reducing the lines of code from 539 to 110 lines with the same exact functionality as before is terrific

**Review by Teqwon-Norman — COMMENTED** [review]
I see you made the overall project less redundant by handling our input validation before we actually reached our functions calls. Reducing lines in the implementation file and increasing a minimal amount of lines in our main.cpp. Overall great work!

**Comment by Bryce-Soghigian** [comment]
Could you add a gitingore and remove all of the random binaries? also add a make file with the reccomended way to run your binary.

**Comment by Teqwon-Norman** [comment]
> Could you add a gitingore and remove all of the random binaries? also add a make file with the reccomended way to run your binary.

Will do

**Pull request merged**
